### ISSUE TITLE
Detector exception occurred

### ISSUE THREAD

**Issue by Phenix123** [cosanlab/py-feat#101]
I have the following code from the example (https://py-feat.org/content/detector.html)

```
from feat import Detector
from PIL import Image
import matplotlib.pyplot as plt
import os
from feat.tests.utils import get_test_data_path

if __name__ == '__main__':
    face_model = "retinaface"
    landmark_model = "mobilenet"
    au_model = "rf"
    emotion_model = "resmasknet"
    detector = Detector(face_model=face_model, landmark_model=landmark_model, au_model=au_model, emotion_model=emotion_model)

    # Find the file you want to process.
    test_data_dir = get_test_data_path()
    test_image = os.path.join('feat/tests/data', "input.jpg")

    # Show Image
    f, ax = plt.subplots()
    im = Image.open(test_image)
    ax.imshow(im)

    # Detection
    image_prediction = detector.detect_image(test_image)
    # Show results
    image_prediction
    image_prediction.plot_detections()

```
But after executing the code, I get the following error

> Traceback (most recent call last):
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\feat\feat\detector.py", line 725, in process_frame
    frame=frames, facebox=detected_faces, landmarks=landmarks)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\feat\feat\detector.py", line 627, in detect_emotions
    return self.emotion_model.detect_emo(frame, facebox)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\feat\feat\emo_detectors\ResMaskNet\resmasknet_test.py", line 769, in detect_emo
    face = self._batch_make(frame=frame, detected_face=detected_face)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\feat\feat\emo_detectors\ResMaskNet\resmasknet_test.py", line 813, in _batch_make
    face = self.transform(face)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\venv\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\venv\lib\site-packages\torchvision\transforms\transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "C:\Users\cat10\Downloads\Практика\faceDetectionOriginal\venv\lib\site-packages\torchvision\transforms\functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given
exception occurred
Process finished with exit code 0

Does anyone have an idea on how to solve this OR know what the problem is with? Thanks!

**Comment by jcheong0428** [comment]
Hi @Phenix123 : Are you using the version from PIP or the master/main branch? The github main branch is currently unstable as we are making a few changes. Would recommend the 0.3.7 release or installing from PIP. Please let us know if you still face issues and we'll take a look! Thanks!

**Comment by Phenix123** [comment]
Thanks, I downloaded verion 0.3.7 from git and the error disappeared. But I get the following error

> exception occurred
Procces finished with exit code 0

Just "exception occurred"

**Comment by ejolly** [comment]
@Phenix123 I've cleaned up a few things in the master branch on github. Can you try reinstalling from there with: `pip install git+https://github.com/cosanlab/py-feat.git` and seeing if you still get the issue?
