### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ritvikagrawal1** [cosanlab/py-feat#109]
```
Traceback (most recent call last):

  File "/home/ritvikagrawal/segmentation_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-13-b9cca46bd865>", line 1, in <module>
    from feat.detector import *#

  File "./.local/lib/python3.6/site-packages/feat/__init__.py", line 11, in <module>
    from .data import Fex

  File "./.local/lib/python3.6/site-packages/feat/data.py", line 176
    print(f"{self.__class__}\n" + "".join(attr_list))
                              ^
SyntaxError: invalid syntax

```

**Comment by TiankangXie** [comment]
@jcheong0428 Maybe it's because there is no self.__class__ attribute?

**Comment by ejolly** [comment]
@ritvikagrawal1 We do not support Python 3.5, so please try again using at Python 3.7-3.9. Feel free to reopen this issue if you still encounter problems
