### ISSUE TITLE
Google Colab errors

### ISSUE THREAD

**Issue by huangpot** [cosanlab/py-feat#125]
Hi there,

I have been able to work with the package well locally, but for some reason the code does not run on Google Colab. The error I get from Colab is and I can't figure out why this is an exclusive issue for colab. Any thoughts would be welcome. See error below when running from the example tutorial (the detector loads well): 

```
> single_face_prediction = detector.detect_image(single_face_img_path)
> # Show results
> single_face_prediction
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/feat/detector.py", line 800, in process_frame
>     frames=frames, detected_faces=detected_faces, landmarks=landmarks_2
>   File "/usr/local/lib/python3.7/dist-packages/feat/detector.py", line 431, in _batch_hog
>     hogs = self.extract_hog(frame=convex_hull, visualize=False).reshape(1, -1)
>   File "/usr/local/lib/python3.7/dist-packages/feat/detector.py", line 600, in extract_hog
>     channel_axis=-1,
> TypeError: hog() got an unexpected keyword argument 'channel_axis'
> exception occurred in the batch
> Since singleframe4error=FALSE, giving up this entire batch result
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/feat/detector.py in process_frame(self, frames, input_names, counter, singleframe4error, skip_frame_rate, is_video_frame)
>     799                 hog_arr, new_lands = self._batch_hog(
> --> 800                     frames=frames, detected_faces=detected_faces, landmarks=landmarks_2
>     801                 )
> 
> 4 frames
> TypeError: hog() got an unexpected keyword argument 'channel_axis'
> 
> During handling of the above exception, another exception occurred:
> 
> UnboundLocalError                         Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/feat/detector.py in process_frame(self, frames, input_names, counter, singleframe4error, skip_frame_rate, is_video_frame)
>     919                         axis=1,
>     920                     )
> --> 921                     out["input"] = input_names[0] if is_video_frame else input_names[i]
>     922                     out[FEAT_TIME_COLUMNS] = counter + cter
>     923                     if newdf is None:
> 
> UnboundLocalError: local variable 'i' referenced before assignment
```

**Comment by ejolly** [comment]
@huangpot Can you try with the latest verison on the `main` branch? I've tried to fix many of these things
