### ISSUE TITLE
TypeError: resnet_fpn_backbone() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by Dean-98543** [cosanlab/py-feat#156]
Hello, when I running the following demo，
'''
from feat import Detector

detector = Detector()
from feat.utils.io import get_test_data_path
import os

test_data_dir = get_test_data_path()
test_video_path = os.path.join(test_data_dir, "WolfgangLanger_Pexels.mp4")

video_prediction = detector.detect_video(test_video_path, skip_frames=24)
print(video_prediction)
'''
 The error is :

'''
Traceback (most recent call last):
  File "E:/Practice/2022_10_MicroExpres/api.py", line 12, in <module>
    detector = Detector()
  File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\detector.py", line 126, in __init__
    **kwargs,
  File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\detector.py", line 250, in _init_detectors
    **facepose_model_kwargs,
  File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\facepose_detectors\img2pose\img2pose_test.py", line 62, in __init__
    **kwargs,
  File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\facepose_detectors\img2pose\img2pose_model.py", line 53, in __init__
    backbone = resnet_fpn_backbone(f"resnet{self.depth}", weights=True)
TypeError: resnet_fpn_backbone() got an unexpected keyword argument 'weights'
'''

**Comment by Dean-98543** [comment]
I fixed this problem by using "pretrained"  instead of “weights”

**Comment by Dean-98543** [comment]
> Hello, when I running the following demo， ''' from feat import Detector
> 
> detector = Detector() from feat.utils.io import get_test_data_path import os
> 
> test_data_dir = get_test_data_path() test_video_path = os.path.join(test_data_dir, "WolfgangLanger_Pexels.mp4")
> 
> video_prediction = detector.detect_video(test_video_path, skip_frames=24) print(video_prediction) ''' The error is :
> 
> ''' Traceback (most recent call last): File "E:/Practice/2022_10_MicroExpres/api.py", line 12, in detector = Detector() File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\detector.py", line 126, in **init** **kwargs, File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\detector.py", line 250, in _init_detectors **facepose_model_kwargs, File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\facepose_detectors\img2pose\img2pose_test.py", line 62, in **init** **kwargs, File "C:\Users\yangm\AppData\Roaming\Python\Python37\site-packages\feat\facepose_detectors\img2pose\img2pose_model.py", line 53, in **init** backbone = resnet_fpn_backbone(f"resnet{self.depth}", weights=True) TypeError: resnet_fpn_backbone() got an unexpected keyword argument 'weights' '''
